# Generated by Django 5.0.2 on 2024-03-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoLearning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tree',
            old_name='type_tree',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='age',
        ),
        migrations.AddField(
            model_name='tree',
            name='description',
            field=models.TextField(default='text'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
