# Generated by Django 5.0.2 on 2024-04-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoLearning', '0004_garden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
