# Generated by Django 5.0.2 on 2024-04-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoLearning', '0006_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('amount_co2', models.DecimalField(decimal_places=4, max_digits=6)),
                ('per_year', models.IntegerField()),
                ('description', models.TextField(default='text')),
            ],
        ),
    ]
