# Generated by Django 5.0.2 on 2024-04-06 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoLearning', '0007_food'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='amount_co2',
            new_name='amount_carbon',
        ),
    ]
