# Generated by Django 5.0.2 on 2024-04-24 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoLearning', '0009_metric'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metric',
            old_name='amount_carbon',
            new_name='amount',
        ),
    ]
