# Generated by Django 5.0.2 on 2024-04-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoLearning', '0010_rename_amount_carbon_metric_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('amount_carbon', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(default='text')),
            ],
        ),
    ]
