# Generated by Django 5.0.2 on 2024-04-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoLearning', '0012_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='amount',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
    ]
