# Generated by Django 5.0.2 on 2024-04-26 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoLearning', '0013_alter_metric_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garden',
            old_name='amount',
            new_name='amount_carbon',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='amount',
            new_name='amount_carbon',
        ),
    ]
